services:
  postgres:
    image: postgres:15-alpine
    container_name: hackathon2-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-leboncoindb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: hackathon2-app-prod
    restart: always
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-leboncoindb}
      NODE_ENV: production
      AUTH_SECRET: ${AUTH_SECRET}
      # Add other environment variables here as needed
    ports:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hackathon2-app.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.hackathon2-app.entrypoints=websecure"
      - "traefik.http.routers.hackathon2-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.hackathon2-app.loadbalancer.server.port=3000"
    depends_on:
      - postgres
    networks:
      - dokploy-network
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
  dokploy-network:
    external: true
